baseURL = "https://scorpiosec.com/"
title   = "Scorpiosec"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "G-662ME9PQBT"
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]

  # Metadata mostly used in document's head
  # 
  description = "A technology blog covering the latest trends in cybersecurity, ethical hacking and machine learning"
  keywords = "technology, programming, tutorials, cybersecurity, software engineering, machine learning, hands-on projects, writeups"
  images = [""]

  # Home subtitle of the index page.
  #
  homeSubtitle = ""

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating system. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true
  
  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Integrate Plausible.io
  # plausibleDataDomain = 'test.com'
  # plausibleScriptSource = 'https://plausible.io/js/script.js'

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = 2023
    rss = false
    copyright = false
    author = false

    topText = ["K-Scorpio"]
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>", "Theme - <a href=\"https://themes.gohugo.io/themes/hugo-theme-hello-friend-ng/\">Hello Friend NG</a>"
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "Scorpiosec:~$"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Startpage portrait 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Uncomment this if you want a portrait on your start page
  #
  [params.portrait]
  path     = "/redscorpio.jpg"
  alt      = "Portrait"
  maxWidth = "200px"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Commento
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Utteranc.es
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Utteranc.es is a lightweight comments widget built on GitHub issues.
  # See https://utteranc.es/ for documentation
  # Uncomment this to enable Utteranc.es.
  #
  [params.utterances]
  #   Your GitHub repository
  #
     repository = "K-Scorpio/scorpiosec"
  #
  #   label used for GitHub issues
  #
     label      = "comment"
  # 
  #   Blog Post <-> Issue mapping. This parameter is optional. Possible values are:
  #      - pathname
  #      - url
  #      - title
  #      - og:title
  #      - issue number
  #      - specific term
  #
     issueTerm  = "pathname"
  #
  #   Theme used: possible values are:
  #      - github-light
  #      - github-dark
  #      - preferred-color-scheme
  #      - github-dark-orange
  #      - icy-dark
  #      - dark-blue
  #      - photon-dark
  #      - boxy-light
  #      - gruvbox-dark
  #
     theme      = "github-dark"
  # 

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/_KScorpio"

  [[params.social]]
    name = "email"
    url  = "mailto:kscorpiosec@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/K-Scorpio"

  [[params.social]]
    #name = "linkedin"
    #url  = "https://linkedin.com/in/darryl-akretchakre/"
    
  [params.author]
    name = "K-Scorpio"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"


defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = "English"
    weight    = 1
    contentDir = "content/en"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  [languages.en.params]
    subtitle  = "Hello Friend NG Theme"

  [languages.fr]
    languageName = "Français"
    weight    = 2
    contentDir   = "content/fr"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
    [languages.fr.menu]
  [[languages.fr.menu.main]]
    
    identifier   = "about"
    name         = "À propos"
    url          = "/fr/about/"
    weight       = 1
  [[languages.fr.menu.main]]
    identifier   = "posts"
    name         = "Postes"
    url          = "/fr/posts/"
    weight       = 2
  [[languages.fr.menu.main]]
    identifier   = "projects"
    name         = "Projets"
    url          = "/fr/projects/"
    weight       = 3
  [[languages.fr.menu.main]]
    identifier   = "tags"
    name         = "Tags"
    url          = "/fr/tags/"
    weight       = 4
  [[languages.fr.menu.main]]
    identifier   = "categories"
    name         = "Categories"
    url          = "/fr/categories/"
    weight       = 5
    
  [languages.fr.params]
    subtitle  = "Hello Friend NG Theme"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 1
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 2
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight     = 3
  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"
    weight     = 4
  [[menu.main]]
    identifier = "categories"
    name       = "Categories"
    url        = "categories/"
    weight     = 5
